# Site settings
title: Charles Cardinaux
email: charles@charlescardinaux.com
description: > # this means to ignore newlines until "baseurl:"
  Experienced web developer in Seattle, Washington
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.charlescardinaux.com" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: charlescardinaux
github_username:  ccardinaux

# Projects
collections:
  projects:
    output: true
    permalink: /projects/:name/
  project_tags:
    output: true
    permalink: /projects/tags/:name/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - node_modules
  - gulpfile.js

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "project_tags"
    values:
      layout: "project-tag"
